version: '3.3'

services:
  mongo:
    image: mongo:6.0.2
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017

networks:
  rabbitmq_go_net:
    driver: bridge
