POST http://localhost:5000/blogpost/ef8ac118-8d7f-49cc-abec-78e0d05af80a HTTP/1.1
content-type: application/json

  {
    "id": "ef8ac118-8d7f-49cc-abec-78e0d05af80a",
    "title": "mstefa",
    "description": "Test1234",
    "body": "matias",
    "date": "2022-10-18T06:14:02.355Z",
    "authorEmail": "mstefanutti24@gmail.com"
  }
